import os
from openai import AzureOpenAI
import time

from dotenv import load_dotenv
load_dotenv()

# Retrieve credentials from .env file or environment
endpoint = os.getenv("gpt_endpoint")
deployment = os.getenv("gpt_deployment")
api_key = os.getenv("gpt_api_key")
api_version = os.getenv("gpt_api_version")

# Initialize Azure OpenAI client for GPT model
client = AzureOpenAI(
    azure_endpoint=endpoint,
    api_key=api_key,
    api_version=api_version,
)

def get_image_description(image_url):
    start_time = time.time()
    """
    Input:
        image_url (str): Full URL to the image file (e.g., JPG, PNG)

    Output:
        summary (str): A Markdown-formatted summary of the image content generated by GPT model
    """

    # Call Azure OpenAI Responses API
    response = client.responses.create(
        model=deployment,
        instructions="You are a helpful assistant that summarizes image content using {image_url} in concise. Respond in Markdown.",
        input=image_url,
        max_output_tokens=10000,
        top_p=1,
        stream=False
    )
    end_sum = time.time()
    print(f"get_image_description Execution Time: {end_sum - start_time} seconds")
    # Return summary content
    return response.output_text
